### PR TITLE
Update unrar usage

### PR DESCRIPTION
**Pull request by guilhermearaujo**
This fixes a couple of crashes I had while running this project on Raspbian.

I'm not entirely sure if this is due different versions of `python-unrar` or `libunrar`. I am using the latest of both.

### CODE REVIEW

**Comment by guilhermearaujo** [comment]
After further investigation, looks like the project currently uses the `rarfile` package, which relies on the fact that Unrar (the application) needs to be installed. This pull request will actually replace the usage of `rarfile` with `unrar` (the library, not the application). This is preferred since the application is not available at all platforms (for instance, Raspbian), while the open-source library can be compiled at most platforms.

**Comment by MestreLion** [comment]
And where can I get the library from? Is it available in Debian/Ubuntu repositories?

**Comment by guilhermearaujo** [comment]
The source code and binaries are available at [WinRAR page](http://www.rarlab.com/rar_add.htm).

**Comment by MestreLion** [comment]
Thanks @guilhermearaujo !

**Pull request merged**
